/*
* tn.h– token type
* progrmmer– 김예지(2176082), 송채원(2076216), 신정화(2271035), 윤하영(2071033)
* date - 2024-04-29
*/
// 토큰 타입 정의
enum tokentypes {
 TEOF, TIDENT, TNUMBER, TRNUMBER,
 TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE,
 TADD, TSUB, TMUL, TDIV, TMOD, TINC, TDEC,
 TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSE, TGREATE, TNOT, TAND, TOR,
 TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN,
 TLPAREN, TRPAREN, TLBRACE, TRBRACE, TLSQUARE, TRSQUARE, TCOMMA,
 TSEMICOLON, TTOOLONG, TILLIDENT, TILLCH
};
