/*
* tn.h – token type 
* progrmmer – 조윤아
* date - 2024/04/27
*/

enum tnumber {TEOF, TIDENT, TNUMBER, TFLOAT, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TADD, TSUB, TMUL, TDIV, TMOD, TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TNOT, TAND, TOR, TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSEQU, TGREATEQU, TINC, TDEC, TPAREN, TCOMMA, TCURLY, TSQUARE, TSEMI, TERROR, TBLANK, TTAB, TNEWLINE};
